# Generated by Django 4.2.2 on 2023-06-24 07:01

import django.core.validators
from django.db import migrations, models
import fruitipedia_app.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='description',
            field=models.TextField(default='description', verbose_name='Fruit Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(default='url', verbose_name='Fruit Image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='name',
            field=models.CharField(default='fruit name', max_length=30, validators=[django.core.validators.MinLengthValidator(2), fruitipedia_app.web.validators.validate_fruit_name_all_letters], verbose_name='Fruit Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='nutrition',
            field=models.TextField(blank=True, null=True, verbose_name='Nutrition Info'),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='first_name', max_length=25, validators=[django.core.validators.MinLengthValidator(2), fruitipedia_app.web.validators.validate_first_letter_start], verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='last name', max_length=35, validators=[django.core.validators.MinLengthValidator(1), fruitipedia_app.web.validators.validate_first_letter_start], verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='password', max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
